hot_wallets.rb: process with pid 2729 started.
hot_wallets.rb: process with pid 15764 started.
hot_wallets.rb: process with pid 19191 started.
/Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:222:in `rescue in io': Connection timed out (Redis::TimeoutError)
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis.rb:676:in `block in set'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis.rb:672:in `set'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/interface.rb:9:in `set'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/ttl.rb:8:in `set'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `block in set'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `set'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:163:in `write_entry'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:36:in `block in write'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/cache.rb:519:in `instrument'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:34:in `write'
	from /Users/yyong/rbdev/peatio/app/models/currency.rb:54:in `refresh_balance'
	from /Users/yyong/rbdev/peatio/lib/daemons/hot_wallets.rb:19:in `block in <top (required)>'
	from /Users/yyong/rbdev/peatio/lib/daemons/hot_wallets.rb:18:in `each'
	from /Users/yyong/rbdev/peatio/lib/daemons/hot_wallets.rb:18:in `<top (required)>'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /Users/yyong/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/hot_wallets_ctl:6:in `<main>'
hot_wallets.rb: process with pid 22144 started.
